name: teachme_ai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.1
  flutter_tts: ^4.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  lottie: ^3.3.1
  equatable: ^2.0.7
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  flutter_native_splash: ^2.4.6
  just_audio: ^0.10.4
  path_provider: ^2.1.5
  uuid: ^4.5.1
  flutter_html: ^3.0.0
  cloud_firestore: ^6.0.0
  reorderables: ^0.6.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.5.4
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff" # Arka plan rengi
  image: assets/icons/logo.png # Splash görseli
  android: true
  ios: true
  web: false
  #branding: assets/branding.png # (İsteğe bağlı) Alt köşedeki branding resmi

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/