// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbW1ST5jJWK5eE3rdNSAa6DaQSQftQgI4',
    appId: '1:998581643705:web:96574a501f0fdc6aa6ee68',
    messagingSenderId: '998581643705',
    projectId: 'teachme-ai-3b8cf',
    authDomain: 'teachme-ai-3b8cf.firebaseapp.com',
    storageBucket: 'teachme-ai-3b8cf.firebasestorage.app',
    measurementId: 'G-TK83NHCV54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo82WDoAoldgUDuwSv2ZCLHaHpfVtCJm8',
    appId: '1:998581643705:android:0bdf1ccf5974ccd7a6ee68',
    messagingSenderId: '998581643705',
    projectId: 'teachme-ai-3b8cf',
    storageBucket: 'teachme-ai-3b8cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfZ7Ooc0-CRJDhdv8U0cuV_nLpUvec4wM',
    appId: '1:998581643705:ios:190cf9e5d0ed8334a6ee68',
    messagingSenderId: '998581643705',
    projectId: 'teachme-ai-3b8cf',
    storageBucket: 'teachme-ai-3b8cf.firebasestorage.app',
    iosBundleId: 'com.yasinaktasdev.teachmeai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfZ7Ooc0-CRJDhdv8U0cuV_nLpUvec4wM',
    appId: '1:998581643705:ios:45fae419c666c2e1a6ee68',
    messagingSenderId: '998581643705',
    projectId: 'teachme-ai-3b8cf',
    storageBucket: 'teachme-ai-3b8cf.firebasestorage.app',
    iosBundleId: 'com.example.teachmeAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbW1ST5jJWK5eE3rdNSAa6DaQSQftQgI4',
    appId: '1:998581643705:web:9d4a09e863a83a7ba6ee68',
    messagingSenderId: '998581643705',
    projectId: 'teachme-ai-3b8cf',
    authDomain: 'teachme-ai-3b8cf.firebaseapp.com',
    storageBucket: 'teachme-ai-3b8cf.firebasestorage.app',
    measurementId: 'G-1WDL91XWTN',
  );
}
